import card1 from './../tarot/1wands.png'
import card2 from './../tarot/2wands.png'
import card3 from './../tarot/3wands.png'
import card4 from './../tarot/4wand.png'
import card5 from './../tarot/5wand.png'
import card6 from './../tarot/6wand.png'
import card7 from './../tarot/7wand.png'
import card8 from './../tarot/8wand.png'
import card9 from './../tarot/9wand.png'
import card10 from './../tarot/10wandclear.png'
import card11 from './../tarot/pagewand.png'
import card12 from './../tarot/knightwand.png'
import card13 from './../tarot/queenwand.png'
import card14 from './../tarot/kingwand.png'
import card15 from './../tarot/1cup.png'
import card16 from './../tarot/2cup.png'
import card17 from './../tarot/3cup.png'
import card18 from './../tarot/4cup.png'
import card19 from './../tarot/5cup.png'
import card20 from './../tarot/6cup.png'
import card21 from './../tarot/7cup.png'
import card22 from './../tarot/8cup.png'
import card23 from './../tarot/9cup.png'
import card24 from './../tarot/10cup.png'
import card25 from './../tarot/pagecup.png'
import card26 from './../tarot/knightcup.png'
import card27 from './../tarot/queencup.png'
import card28 from './../tarot/kingcup.png'
import card29 from './../tarot/1coin.png'
import card30 from './../tarot/2coin.png'
import card31 from './../tarot/3coin.png'
import card32 from './../tarot/4coin.png'
import card33 from './../tarot/5coin.png'
import card34 from './../tarot/6coin.png'
import card35 from './../tarot/7coin.png'
import card36 from './../tarot/8coin.png'
import card37 from './../tarot/9coin.png'
import card38 from './../tarot/10coin.png'
import card39 from './../tarot/pagecoin.png'
import card40 from './../tarot/knightcoin.png'
import card41 from './../tarot/queencoin.png'
import card42 from './../tarot/kingcoin.png'
import card43 from './../tarot/1sword.png'
import card44 from './../tarot/2sword.png'
import card45 from './../tarot/3sword.png'
import card46 from './../tarot/4sword.png'
import card47 from './../tarot/5sword.png'
import card48 from './../tarot/6sword.png'
import card49 from './../tarot/7sword.png'
import card50 from './../tarot/8sword.png'
import card51 from './../tarot/9sword.png'
import card52 from './../tarot/10sword.png'
import card53 from './../tarot/pagesword.png'
import card54 from './../tarot/knightsword.png'
import card55 from './../tarot/queensword.png'
import card56 from './../tarot/kingsword.png'
import card57 from './../tarot/0thefool.png'
import card58 from './../tarot/1themagus.png'
import card59 from './../tarot/2highpriestess (1).png'
import card60 from './../tarot/3empress.png'
import card61 from './../tarot/4emperor.png'
import card62 from './../tarot/5hierophant.png'
import card63 from './../tarot/6lovers.png'
import card64 from './../tarot/7chariot.png'
import card65 from './../tarot/8adjustment.png'
import card66 from './../tarot/9hermit.png'
import card67 from './../tarot/10wheel.png'
import card68 from './../tarot/11strength.png'
import card69 from './../tarot/12hanged.png'
import card70 from './../tarot/13death.png'
import card71 from './../tarot/14temperance.png'
import card72 from './../tarot/15devil.png'
import card73 from './../tarot/16tower.png'
import card74 from './../tarot/17star.png'

let descrip1 = "Although this card symbolizes a creative spark and beginning, the actual way forward doesn't always seem clear-- it's still just an abstract moment of inspiration. The classical illustration for this card has a castle on a hill in the background, which is something I really enjoyed. Here the wand becomes a cane, a handy walking-stick to prod you forward on your upcoming travels."

let descrip2 = "The two of wands is all about actually sitting down and planning the journey that we were inspired to take by the ace. Notably, this is done from a place of safety, so the querant is not yet engaging with the riskiest parts of the coming adventure. Since planning can bring a fair bit of concern that the project will never get done, I've included a rapport between two figures, one much more anxious. Here, the wands become torches illuminating the way forward-- a nod to the suit's associated element (fire)."

let descrip3 = "the three of wands is all about foresight and building up strong foundations to benefit you in the long run. Ospreys use the big nests they build for a very long time. Here, the wands become the building blocks of a sturdy place to root."

let descrip4 = "You've done good work! Now you can revel in your success. This is quite a good card to draw, emphasizing community or familial mirth. Here, the wands become the posts that hold up a festival float as the town celebrates."

let descrip5 = "the five of wands is all about conflict, not necessarily violent, reaching an impasse. i know some folks love having a debate and think it contributes to their growth, but i have largely sworn off combative discourse because i'm too tired, y'all, and it almost always ends in an uncomfortable stalemate. Here, the wands become scepters, those tools symbolic of a heightened sense of self-importance that might lead one to thinking their word is law."

let descrip6 = "The six of wands is all about taking some pride in yourself and acknowledging a personal victory. It's similar to the four of wands, but I think it feels a little more aggressive and reflective of... individuality? rather than the general festive air of the four. This illustration might seem judgy of vanity, but i don't think this card is really negative at all-- everybody should feel entitled to celebrate themselves once in a while! here the wands become candles (remember the suit's element is 'fire'!) to illuminate your victory feast and obscure other's faces. It's your time to shine, baybeeee!"

let descrip7 = "the seven of wands is all about being on the defensive and fighting for your life. Perhaps the stalemated conflict of the five of wands has broken out into a more dire situation, or a more overt fear threatens your wellbeing, but whatever the reason, this card suggests you stand your ground with resolve! Here the wands become martial weapons suggesting not only combat readiness, but discipline. the main characTer MakiNg use of The bo staff is a turtle here, because turtles are defense-oriented creatures, and for no other reason."

let descrip8 = "the eight of wands builds off of the conflicting energy in the seven but implies that now is the time for swift action. This is a card all about moving quickly and seizing an opportunity, usually to get out of a tricky situation! It made me think of parkour, for some reason. And flying kicks. Here, the wands become bardiches, the tools of those who are trying to impede your progress-- but maybe a method to advance even further, as well? I was worried that putting a blade on the wand might hew too closely to the swords suit, but a polearm is still mostly a pole, right?"

let descrip9 = "the nine of wands is like a more dire and hopeless version of the seven. the querant is still locked in some sort of defensive 'fight for their life', but now it becomes apparent that the fight is going to stretch on interminably. Pessimistically, this is a card about being beaten down and realizing the struggle is far from over. Optimistically, this is a card about inner strength and resilience in the face of adversity. I guess I have some thoughts on whether or not we should glorify suffering, but also it is true that in our longest battles i think a bit of self-reflection can help one realize the brilliance it takes to survive. Here the wands become stelae, strange lonely markers on the battlefield memorializing the scars the war has wrought."

let descrip10 = "in tarot the ten represents some form of 'completion' relative to the principal aspects of the suit-- in this case, the wand's focus on ambition and drive is antithetical to the notion of ever 'finishing', so the card is kind of somber. While it does represent the completion of a task, it is more about the realization that the querant's entire life has become a series of tasks. Ostensibly this routine was supposed to satisfy the querant's grander desires and dreams, but the 'rise-and-grind' mindset has replaced any of those loftier ideas with a myopic single-mindedness. The journey has become an endless slog of chores. Kind of a downer! This card usually points to depression and being stuck in a rut. Here the wands become a bundle of sticks, the object of the querant's task and the burden itself."

let descrip11 = "Pages represent a youthful innocence and usually a servile attitude towards the guiding characteristics of the suit. The wands are about creativity and ambition, and so this card often is interpreted with a pretty similar meaning to the Ace of the same suit or The Fool-- it's all about the possibilities allowed us when we are unconstrained by caution of precedent. I think the thing that I see as unique to the page card is the relationship it expects the querant to have with their ambition; instead of being a force at your disposal, here the power structure is reversed. The querant becomes a vessel for a creative force much bigger than themselves-- it's related to those moments when you feel like you have no choice BUT to create or pursue something, those twinges of feeling we like to describe as 'destiny'. It's a little opaque, I think! The page is a salamander because of their mythic association with fire (the element of the wands suit). Apparently this is theorized to have started when people would burn rotten logs the lil lizards were living in, and the heat would make the poor guys run out and seek safety-- people thought maybe they were born from the flame itself! Here the wand is a big paintbrush-- overpowering creative force and all that."

let descrip12 = "Knight cards are some of the hardest for me to interpret-- a lot of decks suggest a personality profile to go along with the knight, but i like readings that are a little less personal. If the page is meant to denote youth, the knight lends itself to readings of expertise and hard work, still with the same servile attitude towards the guiding principles of the suit (in this case, creativity and ambition). This card represents an ongoing quest in search of an established goal-- a disciplined perseverance in service of the querant's will. it's a positive, even prideful symbol of the grind. maybe the most knightly knight there could be! i've always had a bit of a romantic attachment to the idea of some symbol of a person's life still animating to pursue the wants characteristic to that person, the somber sadness of a ghost whose purpose is never realized. here, a knights armor is animated by the fire of ambition itself. the wand becomes a fiery lance, a heroic tool that's only useful if you're rushing forward."

let descrip13 = "Because its divinatory history pretty much (from what i can tell) started around the 18th century, tarot has what i would politely call some reductive and essentialist views about gender, and what i would otherwise call some misogynist bullshit. The queen is thought to have the highest achievement of 'feminine' virtues according to the principle aspects of the suit (in this case, ambition and creativity). For some reason I cannot parse, this has equated to the queen of wands being 'earthy' and 'nurturing' and otherwise a 'mother figure'. Trying to extract the intention behind the place of the card in the hierarchy and still maintain some sort of faith to the original meaning, I've boiled down the queen to representing a form of nuanced, subtle mastery according to the aims of the wands. If the wands are about creativity and will, the most masterful approach i can think of is knowing how to get back up again when you've failed, or things haven't worked out as you hoped. What better avatar for that than the phoenix? It also doubles as a representation of the wands' fiery elemental affinity. The wand in this case is a cigar because I think of cigars as something you smoke when you've accomplished something for purposes you don't understand (i smoked a cigar when I graduated high school, for example), and also because birds smoking cigars is hilarious, to me. FUN FACT: birds usually have two sets of lungs which fill in sequence, so if a bird took a drag of a cigarette, it wouldn't exhale that smoke until the second time it breathed out. What i'm saying is that birds would be really good at vaping."

let descrip14 = "If the Queens represent a nuanced and subtle mastery of the suit's guiding ideals (ambition and creativity), the King represents total, brutish mastery. The King of Wands imposes his will on all around him, according to his own whims and sparks of fancy. He doesn't care about what he's destroying or building-- he is a chaotic force of personality! This is ostensibly a 'good' card to draw; it symbolizes coming into a position of power. to me, the connection to despotism is hard to ignore, and power is kind of a difficult ambition for me to chew on. Maybe it's not for you, though, and that's great! In continuing with the fire/mythological approach to the face \ncards, I wanted the King to be an ifrit or fire djinn, but he ended up being this nasty demon man, almost a shuten dōji-esque dork, which i think is also fine. The final wand becomes a brand, a violent and fiery tool for imposing your vision, and also a pun on the creative side of the wands. big wink!"

let descrip15 = "the ace of cups, like the other aces, signifies a beginning! In this case, the beginning of a very strong feeling. Usually this is extrapolated to mean the querant is about to meet a new romantic partner, but i think it could have to do with a sudden initiation of platonic attraction also! The Rider-Waite Smith imagery on this card has a chalice overflowing like a fountain and a disembodied hand, so I went ahead and ran with it. Wine/alcohol sometimes plays a part in the inhibition prohibition that comes with the fruition of a love admission, so the cup here becomes a wine glass"

let descrip16 = "the two of cups takes the one-sided infatuation of the ace and doubles it into a reciprocal partnership. is this relationship necessarily romantic or sexual? heck nah, though it can be. this is a card about co-conspirators! it might be a more mature bond than the ace, since it incorporates the other's actual existence rather than leaving them an ideal somewhere off to stage left, but i think all the stages of incorporating someone into your life ought to be celebrated. here, the cups become old-timey telephone receivers, because you can't have any sort of partnership without effective communication, which prioritizes listening. Just what are these two up to??"

let descrip17 = "the three of cups is building on the connective energy of the first two cups cards, and now elevates the relationship from a two-person partnership to a group even larger. Old readings of this suggest this must be a card about friendship and insular platonic groups, but i don't see any reason why this card couldn't also point to a stable polyamorous relationship or any number of different situations where there are many people united by mutual affection. this is a card about community, perhaps, or chosen family-- it's highlighting the beauty and harmony of open-ended enjoyment of others. how nice!! if the two is more mature than the ace, this card (which represents the magically and architecturally significant structure of the triangle) is even moreso. here the cups become rocks glasses because friends we are getting slizzard toNIGHT."

let descrip18 = "the four of cups continues the suit's 'cups as relationships' metaphor with this card, but instead of adding one more person to the group, the stability and evenness of four asks the querant to look at the most consistent relationship one has-- one's relationship with oneself. This is a card about introspection and tuning out the noise. Read negatively, this card could suggest selfishness or self-imposed loneliness for the querant. In a more positive light, this card reminds me of those moments in the very small hours of the morning where you feel like you can fly out of the restraints of your own reactive, emotional volatility-- the quiet times when you feel numb but viciously alive. While I was drawing this card on Saturday, i was in the middle of a pretty heavy depressive episode out of which i still haven't totally climbed. as i tried to think of how best to illustrate the portents of the card, i noticed the empty mason jars around me that held my half-drank drinks, the physical detritus of my emotionally overwrought state. drawing this briefly pulled me out of my feelings, so in a way it served the purpose of its own intended reading! that's maybe a little cheesy and too personal for how i usually get with these, but there you have it: that's why the cups are mason jars here, folks!"

let descrip19 = "the five of cups is a card about disappointment and loss, traditionally represented as a cloaked figure mourning the spilling of three of their five chalices. i didn't stray too far from that, as i think most of the traditional imagery is pretty important to the reading. The fact that the figure isn't focusing on the two chalices that are still upright is likely pithy, criticizing pessimism in the face of tragedy. That sort of wry judgment feels misplaced, to me! The loss of anything, no matter how trivial it appears from the outside, can feel monumental. What if he was really thirsty, and now he won't have all the juice he wants?? That would totally ruin my day. However you take this card, it asks the querant to contemplate loss and its accompanying grief. a good thing we are not often encouraged to do, imo. The card, with its quasi-ironic maudlin melodrama, reminded me of those old romantic paintings that were meant to depict melancholy, usually with a young buck in the throes of emotional turmoil in the midst of a gothic ruin. Caspar David Friedrich might be the most useful touchstone for what i'm thinking? The gothic as a literary mode often exaggerates emotion, particularly sadness and agony. That's where my touch on the \nimagery comes in! Chalices felt appropriate for cups in this card because of their often frivolous ornamentation and their often heightened spiritual importance (the Holy Grail is one of the most famous quests, right?)."

let descrip20 = "the six of cups is a card all about childhood. this can be taken many ways, but the most common is to read this card as a portent of nostalgia and all the complicated emotions that engenders. maybe this card is an omen that the querant will experience the exuberance and joy people project onto children! but to me, nostalgia and memory can be a beautiful trap; it's a comfortable grave you build for yourself. if you spend too much time fixating on youth itself, you miss out on the wonder that was actually central to it-- so this card depicts a child enthralled by something forever out of sight. here, the cups become jars of fireflies. catching these critters, to me, is a distinctly youthful activity that actually seems pretty sinister when you think about it."

let descrip21 = "the 7 of cups is a card with some wild imagery, and has been associated with fantastical thinking and hallucinatory visions. like most of the sevens, it represents a way to laterally think about the suit's guiding rationale (in the case of cups, emotions). I like the idea that contemplating your emotions sideways necessarily alienates your own perspective. This sort of ego death is often what's sought after in experimentation with psychedelics! actual effects, i think, will vary. the 7 is a card that presents you with an abundance of options, but most of them upon examination are nonsensical and vaguely sinister. to me, this is a card heavily associated with the 'wheel of fortune' or 'chance' major arcana card with its multiple offerings. perhaps it is encouraging you to try to expand your thinking, or perhaps it's telling you that the path ahead is muddled and dangerous no matter how you proceed. some especially negative readings of this card indicate it as a warning; this may suggest the querant is overindulgent in their own fantasy life. Here the cups become sacrificial dishes for offerings to gods you might find on alters. surrendering yourself and experiencing extraordinary visions is something i have a hard time extricating from spirituality, even though spirituality is necessarily constructed from your own limited perspective."

let descrip22 = "our card today is the Eight of Cups, which parallels the four in that it attempts to impart some sort of stability over the governing attribute of the Cups (emotion). In this case, the 'stability' comes from the rote predictability of toxic emotional cycles. I'm thinking of the constant pattern of highs and lows in emotional situations that have become abusive or otherwise detrimental-- whether they come from personal relationships, jobs, or anything, really! While these negative thought loops can feel safe and familiar even in their painful repetition, i think they're best to ultimately avoid. This card optimistically points towards the querant abandoning their current emotional spirals, hopefully to find better things! Here, the cups become the cages from which one must break free. Perhaps a little abstract, as cups go, but it's the only suit to include vessels."

let descrip23 = "today's card is the nine of cups. as we approach the end of the numbered cycle for cups, we start getting cards that deal with emotional 'completion'. in this case, the nine deals with the emotional fulfillment of fantasy and dreams. i have had more than one dream that, for reasons inexplicable considering the dream's usually nonsensical content, has bled into and uplifted my mood for weeks. the weird, hollow happiness that echoes in our mind after a chance blissful dream or fantasy is a very powerful feeling, and it's what this card is all about. this card is generally thought to be a Very Fortuitous one to draw: it points to the querant experiencing that level of emotional satisfaction soon. Maybe they will have a dream themselves, or perhaps something in their life will seem 'too good to be true' for at least a little while. a happy card! in considering this one, i didn't want to go very straightforward. i started thinking about coleridge and stately pleasure domes, about winsor mccay and little nemo's idyllic yet vaguely threatening dreamscapes. what resulted was this bizarre fantasy castle atop so many stilts, the cups adorning the tops of its tall spires for no reasonable purpose. maybe a nice place to visit in a dream."

let descrip24 = "the ten of cups is like the nine in that it's about emotional fulfillment. although the nine promises the ideal achievement of fantasy, it ultimately can't deliver in reality. the ten, in a more 'mature' way, is about the feeling of satisfaction gained from the completion of real goals and nurturing actual relationships. it's a nice card to get! it's usual taken as a portent that your efforts will pay off soon and lead you to a feeling of gentle, unpretentious self-satisfaction. what better image for something like that than the kind smile of an old woman in her garden? here the cups are-- well, they're buttercups, aren't they?"

let descrip25 = "Pages tend to represent youthfulness and a servile attitude towards the guiding aspect of the suit (for cups, this is emotions/sensitivity). the page of cups, to me, is symbolic of those unconscious little impulses and fleeting tiny thoughts you get throughout the day that you can't trace back to any rational origin. those small feelings you can't quite name. perhaps drawing this card is telling the querant to pay more attention to those little urges! or perhaps the querant is just going to be feeling particularly unsettling ones soon. the cup here is a little teacup, an afternoon beverage to sit around and meditate on, and the page itself is a friendly little guy that's definitely not attached to anything more threatening under the surface! no need to look any deeper, friends."

let descrip26 = "the knight of cups, or 'cavalier' of cups as i'm calling it to differentiate its letter from the king, is a card all about action as relevant to the guiding aspect of the suit, emotion. this is a card about what your feelings and love drive you to do, all of the reckless bold brave and boneheaded stuff 'romance' might've enticed you into. i would probably interpret this card to mean that the querant ought to throw caution to the wind and pursue a strong emotional conviction regardless of how uncertain it may seem. basically: shoot your shot! as for the imagery, the mythological figure this face card incorporates is the siren. maybe it's foolhardy to steer your ship into the rocks to get closer to her, or maybe it's sooo romantic! here she's holding a conch shell in place of a cup, a signifier of her musical talent and the way that music often feels tied more strongly to and centered around our emotions. the history of conch shells being used as trumpets to evoke religious or at least spiritual reverie is really interesting (check out Chavín de Huantar, for example, if you want to learn more!) and converges nicely with this card's intent. why is the siren a monster instead of a beautiful woman? mostly because i think the idea of the siren transcends the weird fetishization found in white men's anachronistic translations of the odyssey."

let descrip27 = "queens tend to represent mastery of the principal aspects of the suit, but in a subtle, non-absolutist sort of way. with that in mind, the queen of emotions here is symbolic of reckoning with your darkest and shadiest of feelings, rather than being terrified or willfully ignorant of them. the mythological figure personifying this message in this deck is the selkie. is the myth of the selkie a story of surviving abuse? of a conditional love? of the grief of motherhood? whatever is going on, it's a complicated tale that can hold many emotional truths, but the one thing that seems clear is that the selkie sticks to following her convictions no matter how they may look from the outside. this card asks the querant to look deep down and ask if there isn't something they're ignoring-- if they're truly happy on land with a stale love, or if they've merely settled. here the cup is a bucket because it's a beach innit"

let descrip28 = "king cards represent mastery of a suit's principles in an absolute, inescapable way. therefore, the king of cups is symbolic of total control of ones emotions. emotions can be distracting, disorienting and otherwise obstacles to a life well lived, and so the ability to completely tune them out can be desirable. however, i also think feelings are really important to being well-rounded human beings! so this card has kind of an off-putting aura about it for me-- it shows power, but what was sacrificed? the querant would have to discern that for themselves. the mythological figure associated with the king in this deck is the Kraken (the element of cups, as a reminder, is water). i remember reading at some point that since cephalopods developed intelligence along a totally different evolutionary track long ago, they are the closest to having a completely alien perspective as \nwe have access to on earth. i don't know if that's true, but it sounds neat! and it resonates with the inhuman capabilities of the king. the cup here is a submarine (modeled after bushnell's 'american turtle')... how puny human artifice appears to the great beast below."

let descrip29 = "the ace of coins is meant to represent a sudden shift for the better in terms of either money or physical well-being. the coin here is a peppermint (candy) sprouting amongst peppermint (the plant). candy is a nice physical reward that provides an immediate good sensation, and peppermint has long been touted as an aid for myriad health problems. a humble offering from the earth, and a nice place to start a whole new suit."

let descrip30 = "today's card is the two of coins (or pentacles), which is maybe the most basic a 'two' card can be in tarot-- it represents balancing two opposite pursuits in your life. this is a card about work-life balance, or work-other work balance, or life-love balance-- any number of dichotomies that it takes a lot of finesse to find moderation between. in the rider-waite smith art this is represented by a juggler, but people who are adept at this always strike me as a little magical, and i guess im a little bit in the spirit of the season. here the coins are two yo-yo's, two rhythmically fluctuating foci."

let descrip31 = "todays card is the three of coins (or pentacles). this card mirrors the three of wands, in that it's about working towards an envisioned goal or ambition. however, because of the grounded nature of the coins suit, this card deals specifically with the mundane, humbling work of actually practicing a skilled labor and slowly honing your expertise. i like this card a lot! not necessarily my illustration, but i love the focus on any pursuit as a series of practical efforts. i find thinking of illustration or any of my hobbies as slowly building through trial and error to be really rewarding. if you ever watch somebody who has devoted their life to learning a craft it's pretty mesmerizing! here the coins are wheels, something that gets you from point a to b reliably through repetitive motion and also the object of our wheelwright's dedication."

let descrip32 = "combining the static stability of the fours with the earthy materialism of the coins results in a card that is firmly about the querant's comfort zone. this is a card about being complacent and stagnant, hoarding material possessions or deriving excess (inappropriate?) joy from them. it seems like kind of a judgy one! the rider-waite smith artwork features a miserly king clutching his gold, and a lot of readings refer in some way to greed or gluttony. that is definitely one way the querant could receive this card. i also think sometimes it's fine to indulge in the pleasant physical things you've amassed for yourself, and i think being condescending about materialism has some serious classist connotations. just be careful while you're nibbling on your treats and luxuriating in being a lil rat that you don't wake up to find you've actually neglected yourself and are in a pile of garbage, imo. otherwise you're good, im giving you permission. im your dad now. the coins here are cookies, definitely an 'unnecessary' indulgence but if you think cookies shouldn't exist AT ALL you probably have some very weird opinions on things that i don't want to hear."

let descrip33 = "todays card is the five of coins, a card which sometimes is subtitled 'dark night of the soul'! brutal! it takes the material comfort of the four and locates it squarely out of the querant's reach. while warmth and security are nearby, our subject must continue to roam the cold streets. maybe something is profoundly out of sync with the querant's spiritual life, or maybe it's as obvious as having lost something significantly materially valuable, but no matter how you slice it this card is a rough draw. the art here is a little disorienting, maybe, but reckoning with any level of poverty can really rearrange what you thought you knew about the world, in my experience! here the coins are the decorations on a warm \nwindow-- shedding light and appearing beautiful, but ultimately a poor facsimile of actual comfort."

let descrip34 = "todays card is the six of coins, a card which is all about C•H•A•R•I•T•Y. it is purposefully vague about whether the querant is on the side of the donor or recipient. giving alms is traditionally a morally unambiguous thing--and there are plenty of folks who need assistance and who i fully advocate supporting without any of this philosophical junk-- but i think this card calls special attention to the way that a society built on the expectation of charity towards the marginalized is deeply flawed. everyone should have enough!! the rich should not get to pick and choose who deserves support, and it should not be looked at as anything other than reparations when a little charity goes the way of the abused. i hope that this card would cause the querant to question the role they are signaled as playing in this interaction, recipient or donor, and to refocus their energies as much as possible according to the injustice that provides the framework. also, hopefully this goes without saying but the charity here need not be strictly financial in nature. obviously i think philanthropy can come across pretty predatory, and that definitely colored the direction i took this card. however, millipedes (which are not this big) are in reality super sweeties and don't harm much of anything since they are usually detritivores and eat plant garbage. so also this card is more complicated than that! because i do think giving freely of one's \nself is a really good thing, even if it feels unnatural the way a bug feeding baby birds feels unnatural, and i don't want to discourage the human impulse to help out. this card is about a lot of things! here the coins are lil chicks, unaware of their role beyond their own personal hunger."

let descrip35 = "today's card is the seven of coins, a card that is all about cultivation. this card feels a bit odd, for the coins suit! like it feels like it belongs with the cups, instead? it has to do with the long process of growing something valuable through minuscule efforts, often referencing a human relationship or a flourishing career. this card's emphasis is on the unseen and often under-appreciated hours of labor that growing requires. as i was contemplating how to depict this, i was thinking a lot about this quote from bertolt brecht's psalms (transl.): 'the solitary tree in a stony field has a strong sense of futility. it never saw a tree. there are no trees'. sometimes the painstaking ordeal of growth is a lonely futile thing, i guess. this feels more in line with the grounded cynicism of the coins than other interpretations of the card, to me. here the coins are, well-- pentacles. they are grounding totems, hung with care from a tree which will, providence willing, blossom again in the springtime. regardless, they'll swing in the wind, a reminder that at some point, attention was paid. is this description particularly pretentious, even for me?? please forgive me!! i went to grad school for literature, empty gestures of \nself-importance are my bread and butter"

let descrip36 = "the eight of coins is our card today, and it's all about knowledge, studying, and learning the inner workings of something practical. i think i have kind of a child's reverence for audio engineering and mixing and music theory in general, since it's a skillset i wholly do not possess. i can pluck out a few chords on the banjo but that's pretty much it for me. folks can make entire soundscapes out of beeps and boops and that's pretty cool! thematically i think this card is pretty similar to the three of the same suit, but it's more oriented towards being a student than a master, and more oriented towards abstract thought than practical skill. here the coins become some vinyl for our little producer to spin and spin."

let descrip37 = "today's card is the nine of coins, a card that represents a self-centered fulfillment of the guiding aspects of the suit (material health and wealth). it's usually represented by an aristocrat strolling in a garden, and it generally indicates that the querant has reached a point of well-earned satisfaction and achievement in some meaningful physical sense. it's a good omen, for sure! while drawing this card, i was thinking a lot about the beginning of moebius's le monde d'edena, a story BROADLY about two genderless space mechanics who crash on a foreign planet that is seemingly an uninhabited paradise. the first act deals with their struggles as they eat the organic food and breathe in the untreated air and remember that they are man and woman and are tempted by each other. it's dated and quasi-biblical and mostly serves as the artist's soapbox to talk about how we should all eat fresher food, a moral i take a lot of umbrage with (let's not mention the culture of assault the book tacitly seems to endorse). i find myself interested in the prior concept of weird detached satisfaction as one roams through the infinite cosmos and sees incredible things, unbothered by material thirsts which are quenched immediately. so i tried to channel that imagery here, obviously inspired by retro sci fi comic art. here the coins are moons, those heavenly bodies the querant may feel aligned with as they experience bodily fulfillment chomping on their space noodles."

let descrip38 = "like all tens, the card is meant to represent a sort of satisfaction and completion of the guiding aspects of the suit-- for coins, this is materialism. usually, this is interpreted to mean something pithy regarding the physical work the querant has done on this globe-- whether that's the relationships they've formed, the art they've created, the wealth they've amassed, or the ideas they've proliferated, this is a card about the querant's sustained legacy. usually this is a good omen-- it points to something positive about the querant's impact, or maybe just indicating that the querant has HAD an impact on the world is positive enough (though that seems wrapped up in some questionable ideas of 'life's purpose'). in regards to the art, i kind of struggled! i ended up landing on thinking of all the tiny universes i've dreamed up over the years creating comics and reading stories and talking to my loved ones. physically realized or not, it's pretty cool that all those cosmoses are tangled up somewhere in my brain. i guess this card's image is sort of the vain & self-aggrandizing hope that if anything survives my withered physical form, it's that sort of creativity! here the coins are little bubbles that surface the wreckage of society, filled with objects unknown and possessing their own secret life."

let descrip39 = "pages represent a youthful naïveté and earnest beginning with regards to the principal aspect of the suit-- for coins, physical health and wealth. this card tends to signal an opportunity to start a new craft, or perhaps just renew one's perspective on an old one. it can also be an omen of imminent financial windfall like a lot of coins cards. the page is the mandrake, a root vegetable with a long medical history and mythologized for its psychoactive properties and oddly humanoid shape. coin cards are associated with the element of earth and also often with physical well-being, so this curious little guy seemed appropriate! here the coin is a penny-- a lucky indication that maybe something good is about to start."

let descrip40 = "todays card is the Knight of Coins (stylized here as 'cavalier' in order to avoid confusion with the King card). this knight's earthbound temperament makes them a tribute to what i will lovingly term the Slog. you know that feeling when the sheer enormity of what we must do as human beings to continue physically surviving starts weighing on you? when you can't believe you have to get up and tend to your bodily needs and also go out into the world and do a series of often apparently meaningless tasks just so that the fragile little peace you've constructed for yourself doesn't blow apart like a house of cards? this knight is a champion of that routine, an emblem of the endlessly mundane but extremely necessary. it's a card about getting to work-- not necessarily because the work is good or you care about it or you are working towards something bigger, but because The Work Needs Doing. depending on how this card is drawn, perhaps the querant should prepare for a long period of seemingly inconsequential practice, or perhaps the routine needs breaking and this card serves as a warning. either way it seems like the querant is gonna be B•U•S•Y. the mythical figure associated with this face card is the artificial giant made from mud or clay. i feel like the most common reference point for this concept is the golem from Jewish folklore? but these weird automatons crop up in stories for as long as \nsculpture has been an art form and human facsimile has captured our hearts. even galatea could get in on this action! there is something dehumanizing about committing to the Slog, maybe-- but something comfortable and rewarding about being a little machine, also. here the coin is the magic circle -- a ritual in a lot of esoteric practices that serve to ground and direct wayward spirits."

let descrip41 = "todays card is the queen of coins. queens tend to represent nuanced mastery of the driving aspects of their suits. this makes the coin queen someone who is deeply comfortable with and enriched by the physical world-- she is a great lover of animals, of sensual and worldly comforts, of fulfilling her bodily desires, and probably of kinky sex. hers is a warm reign, if a little insular. like a lot of queen cards, traditional interpretations have foregrounded the idea that this card represents a quasi-maternal relationship, a sort of gaia-like 'earthmother'. i usually resist these readings because i think they're grounded in a pretty blatant misogyny, but this one i let squeak by just a little. if any of the queens are going to be caregivers, it's probably this one! this is a card that signals to the querant a period of nurturing fulfillment and of realigning with their grounded material needs. the mythical figure associated with this earth-attribute face card is the dryad, nymph of the oaks"

let descrip42 = "the King of Coins winds up our earthly suit this week. he's a dude that's all about the bottom line -- accumulating wealth and fame and success and all the sorts of things that can make your life more comfortable under capitalism. because of his incessant materialism and absolute dominion over the physical, this is a card with close ties to the major arcana card The Devil! it's usually taken more positively than the devil is, especially at first blush, but this guy is definitely about absolutely controlling his surroundings to give him the cash and luxury he desires. the mythological figure associated with this card is the Green Man, a ubiquitous figure of rebirth and renewal in folklore. i mostly chose to incorporate him because this card is all about that green, man. the coin in this case is the very concept of money. i find it a little funny that because of tarot's elemental mapping, 'nature' and 'earth' get lumped in with 'physicality' and 'materialism'. people who are inclined towards magical thinking, in my experience, tend to attribute a lot of metaphysical and magical potential to the natural world. tarot kind of flouts that (maybe accidentally) and i think this card specifically calls attention to that ironic counterposition. fun to think about!"

let descrip43 = "the swords suit is all about reason and intellectualism and is associated with the element of AIR. the ace of swords kicks off with a very leading idea of what 'reason' means in magical contexts-- it is a definitive, precise tool which settles things in absolutes. in short-- it is a blade! yes or no, to live or die: this is a card which signals to the querant that there is no room for second-guessing. as surely as the guillotine cuts, so too must logic dictate a (grim) finality regarding the question posed. the immutability of rational utilitarianism seems naturally at odds with the perspective of a relativist template like tarot, and so many of the cards in this suit will SEEM pretty bleak-- but a sword is a useful tool, even if it serves a single purpose. sometimes you have to sever something-- but oftentimes you do not! that's the idea behind the ace of swords: put your uncertainty up to this harsh light."

let descrip44 = "today is for the two of swords, a card which usually is associated with the imagery of clashing or crossing blades. it generally signals two different rational opinions being at odds, and is an omen of conflict and struggle. i think there's something to be said about the necessity of two trains of logical thought never quite being perfectly parallel and so having to occasionally bump into each other and set off some sparks. no relationship can get by totally without argument! for that reason the two swords here form a forfex-- a pair of scissors that are designed to come together and can accomplish different sorts of cuts than a solitary blade could on its own. everything that rises must converge and all that. obviously i didn't want to FULLY dismantle the distressing energy of the card, so the scissors here are employed in an act reminiscent of the conflict in that famous mock epic by Alexander Pope. the Baron of the piece wants Belinda's hair because he is lustful, and she would like to keep it because she is vain, a conflict of rational opinion so impossible to solve that Pope could only conclude it by having the tress literally ascend into the heavens. obviously i am working in Pope's very own mode of satire here, but i DO think haircuts can be very emotional and stressful experiences, maybe because a decent one usually necessitates two different people coming together to express their vision, even though the stakes are entirely with one person. I don't know! this card stirred up a lot with me, maybe because i recently chopped off all my hair."

let descrip45 = "today is a very special one because it is one of my favorite cards, the three of swords. i think the rider-waite smith iconography of this card, three swords going into a heart, is one of the most recognized tarot symbols, especially for a minor arcana! the card itself feels like it's linked to Death and The Tower in terms of its portent. the three of swords is a sign that the querant's emotional knowledge of something has been absolutely eviscerated by the reality of the situation. put a different way, this is a card about a harsh wake-up call, the overwhelming feeling of realization when denial finally fades away and you are left with the cold hard truth. i think it's usually pretty indicative of an upcoming sea change in the querant's life, and although it's probably ultimately good to do away with fantasy, this card does not forecast a pleasant transition. the iconography here is maybe a little abstract, but it kinda boiled out of me as \ni was making the card. the main figure was meant to be some sort of soothsayer or priest figure, surrounded by the idols of a false gospel, finally skewered and unable to maintain the charade. i like how this one came out! thanks for reading."

let descrip46 = "todays card is the four of swords, a card that represents the intersection of a four's stability with the precision of analytical thinking. i have a tendency to catastrophize when faced with ambiguity-- to assume the worst possible outcome and elaborate endlessly on that in a little doom spiral-- and i think it comes from me trying to rationally think through my anxiety. if i figure out the worst possible way things could go, and then figure out how to deal with it, i won't have to be anxious anymore, right? anyway it's a pretty huge activator for stress in its own right, and this card asks us to chill out a little. the time for analysis is past and we can focus on calming our thoughts. maybe meditate! let those old swords rust where they are, the beast is long since slain. this card is sort of a nice reprieve after the more ghastly cards in this suit, and i tried to incorporate a nice low-stress image. if you pull this card, you could probably be a little kinder to yourself! i love you! thanks for reading."

let descrip47 = "the five of swords is all about adversarial relationships we structure through our rationale. it's about how humanity tends to frame things in terms of 'us' and 'them'! there's not a whole lot i feel like i can say about that without sounding kinda hokey, but i think even the most binary-avoidant among us skews into this way of thinking out of sheer necessity from time to time. relationships are really complex, and feeling like a part of a community is necessary but implies the violence of exclusion! this card indicates that the querant will experience strife and tension due to ideological differences with other thinking minds, perhaps even outright conflict. will you fight? or will you perish like a dog? either way this card kind of insinuates that you are going to get your ass handed to you, so, yknow, watch out for that. i like to think of this card as \nsort of a mirror to the seven of wands, a card that's all about the valor of standing your ground and which laughs at the idea of being outmatched. here the opponent has an irrefutable upper hand and your guard is down. so i mirrored the composition of the other card! was this lazy? i had a lot of fun doing it, anyway, and i like the outcome. so it's fine with me!!"

let descrip48 = "the six of swords is a card about journeys and momentum. specifically, this card signals a shift away from a mindset that, while beautiful and fulfilling at first blush, no longer serves the querant when considered at length. if the three of swords is about a harsh wake-up call, this card is about the consequence, a somber journey through the broken illusions of obsolete idealism to a place unknown. will things be better there? hard to say at this point! the rider-waite smith illustration notably depicts a hooded traveler in a boat, an image that i find so evocative it felt weird not to include! the themes also made me think of the marvel that ancient ruins present to the modern voyeur. if buildings were erected and crumbled prehistorically, even the most thoroughly researched artistic rendering of what they might once have been remains a shallow fantasy. all you can do really is sit and think and try to move through them! i really relish feeling small and unimportant when it's the direct result of natural majesty (it helps me stay grounded, i think!), and a romantic part of me believes that exposure to things much bigger than you in the world is a good way to train up your humility. i think that's the right mindset to have when you're doing the work this card asks of you."

let descrip49 = "the seven of swords, a card that is about using a keen intellect to outwit and outmatch your opponents. this is a card that elevates the tricksters and the silver-tongued, a real love letter to the robin hoods and coyotes of myth. generally i think readings of this card frame this way of overcoming adversity as negative or dishonorable-- i guess because usually it involves some level of deceit! but we all get a kick out of a hero who wins because they're a little smarter, rather than just because they're Good or The Strongest, right? whether you think this card advises the querant to use their wits to overcome a nearing obstacle or admonishes the querant for relying on trickery too often really depends on your idea of what's fair. tarot tends to have a pretty disapproving attitude towards intellectualism in general, so take that as you will! i didn't stretch my brain too much on the art for this one. i was thinking of some sort of heist scenario because those usually involve a Mastermind, and the hyper-competent gentleman thief feels like an archetype that is immediately recognizable both visually and culturally. also i was thinking about how cute raccoons are, so we ended up here. an aside: thinking about robin hood made me think of goemon, which made me think of benkei, which seemed serendipitous because he famously had seven weapons. i ended up not using that angle at all, though. oops! maybe if you make your own deck you can use that!"

let descrip50 = "if the four of swords is about taking a break for mental serenity to pull up from an anxious nosedive, the eight details what happens when you're unable to stop the spiral. this is a card about the feeling of paralysis you get when you feel solely able to act and speak wrongly due to catastrophizing, the trapped sinking feeling of being stuck in your own head and unable to do even the simplest thing correctly. it's a feeling i relate to viscerally, especially when i'm in a conflict situation! this is generally considered one of the worst cards to draw in a reading, and it's also the first card associated with the star sign Gemini, which just so happens to be my sun sign. haha! i tried to illustrate anxious freezing without getting too dark, but if you pull this card... you've got my sympathy, bud."

let descrip51 = "todays card is the nine of swords. have you noticed that all the nines have sort of a dreamy energy to them? my best guess as to why this is is the nine in tarot has been traditionally associated with the esotericist interpretation of yesod, which is the sefirot associated with imagination and lunar energy. regardless, that energy gets channeled through the swords' narrow and over-determined lens to give us a card that's all about nightmares and intrusive thoughts. this card is sometimes subtitled 'Cruelty' and i think it mostly has to do with the cruelty our mind can inflict on itself. the rider-waite smith iconography has a figure weeping upon apparently waking, and this card can either be interpreted as their fright and desperation at the ways the mind can twist in on itself, or relief at discovering that those blighted apparitions are ultimately immaterial. use your discretion! i am not really a horror artist and i didn't want to mess with the vibe of the deck too much, so my silly little horse-faced ghosts here are drawn in a starkly different style from the figure waking in the real world. maybe this is jarring! but nightmares tend to be that way too. have a creepy day y'all!!"

let descrip52 = "todays card is the ten of swords. i've mentioned before that ten is the number of completion in tarot, and so the swords represents complete intellectual understanding. one might call it intellectual 'overkill'! the card insinuates that in completely knowing something inside and out, you remove the magic and mystery that could accompany it. while in some sense you stand 'triumphant', you can't help but admit that you've strangled the life out of something beautiful in trying so hard to answer every question. this card is usually a signal to the querant that they should start over somewhere else-- that there is nothing left to gain from probing this dead horse any further. i think there's something interesting in believing that retaining some ambiguity is the way to really appreciate things. keats called this 'negative capability'! maybe it's unscientific to think that hard answers can be unsatisfying in the end. every interpretation of the imagery for this card i've ever seen has been at least a little gruesome. i didn't shy away from it! hopefully it's not too yucky for the rest of my deck."

let descrip53 = "todays card is the Page of Swords, a card representing new beginnings and naïveté with regards to the principal aspects of the suit-- intellectualism and rationality, for swords. this card can be interpreted as an urge to begin a new area of study, to take up a new line of pragmatic research or thought. it also has a lot to do with the sheer enormity of possibility that confronts someone at the beginning of a journey about which they know very little, and the inability of a little seedling to make the necessary choices on their own. whether you flourish in loamy soil or wither in an arid badlands, it's up to which way the wind blows when your ability to apply logic is underdeveloped. if you recall, wind is the element associated with the suit! this card can be a little scary, but it's also a card of potent possibility. time to let go and hope for the best! the page here is sort of a fantasy version of a dipterocarp."

let descrip54 = "todays card is the knight of swords, stylized 'cavalier' to avoid confusion with the king card. the knight of swords represents intellectualism given a driving edge and ambitious spirit. it is the urge to classify, to build arbitrary dichotomies, to declare that one knows what's right even when they hardly know anything at all. this card clarifies a lot of the earlier swords cards, about 'us vs them' and 'intellectual overkill', as signs of imprudent zealotry to imperfect rationality. this is passion for the mind with none of the mastery, and we all know someone who fits this condescending role (and have probably slipped into it ourselves on embarrassing occasions). this is a card that urges humility about what the querant thinks they know. due to the swords being associated with wind and also with death, i thought it fitting to include mythological figures in their royal family that have to do with heaven or the afterlife. the knight here is a psychopomp-- a guide to the land of the dead. of all the things that seem intellectually imprudent, saying that it was 'someone's time' to die feels especially egregious. death has no grand motive and takes without bias, and to assert otherwise usually casually endorses cruelty. maybe this psychopomp believes they have agency in their role, but are acting according to principles which they don't understand. also, the dog is a moddey dhoo! (all the knights in my deck have had associated animals, if you've noticed!)"

let descrip55 = "today's card is a queen, which represents nuanced mastery of the guiding principles of the suit. for swords, this is the rational mind! the queen is the sort of person that you meet and feel immediately that they are brilliant. they always seem to be one step ahead of any argument and have thought things through to a level beyond what you had considered. they aren't necessarily showing off or being didactic, but talking to them always seems to provide new and interesting perspective because of how engaged they are with everything around them. that said, the queen does not suffer fools and can seem intimidatingly judgmental. what's worse-- you tend to agree with her judgment, which means she can spark a lot of feelings of inferiority and cravings for approval. the queen here started as \nthe old greek myth of the harpy (you may recall that the element associated with swords is wind), so i took a lot of design cues from harpy eagles. but pretty quickly i also decided to incorporate elements of seraphim, since angels have similar unapproachable and judgy energy imo. i like her! but i think i would be stressed out being friends with her."

let descrip56 = " todays card is the king of swords, the symbol of absolute dominance over the mind. this king brooks absolutely no truck with magical thinking or any kind of wistfulness-- they are instead a practical, rational being that generally comes off cold to the point of cruelty, even if they are almost always right. this is the person in your life that takes 'tough love' to the point where you aren't sure love is really a factor anymore. they would be easy to ignore if they weren't so consistently correct in their observations. like all the kings, i think the mastery element is meant to exceed where we're actually all supposed to be-- the king's jaded pessimism and refusal to acknowledge that there's anything beyond hard logical thinking ignores a lot of what makes life livable, in my opinion. sometimes it's an outlook you have to have, i suppose! the master of wind here is depicted as \na sort of wyvern or wyrm or dragon or whatever fantasy word you like for winged serpent. im partial to the part of dragon mythos that informs us they are wise and ancient beings, because in practice they almost always come off as \nbig angry greedy dummies. i guess if i was so much smarter than everyone around me and lacked soft knowledge like human empathy, i might become a curmudgeonly recluse also. either way, they're beautiful and demand respect and have places of high power in a lot of legends, but they are also almost always something the hero ought to overcome. i think clinging solely and desperately to intellect is similar in a lot of ways."

let descrip57 = "the fool represents, ideally, the blankest of slates-- someone without direction beyond whimsy. Even the aces of the other suits indicate that there is a likely path for inspiration and new beginnings to follow-- not so with the fool. instead the fool is completely free, with all the negative and positive attributions that can come with that. this usually indicates the onset of completely new and unfamiliar circumstances for the querant, or at least suggests that acting as if one is totally inept is the most appropriate way to proceed, to learn, and to grow. a lot of interpretations of tarot indicate that the major arcana tells a sort of story, and that the star of that story is the fool. i don't like to give any one card that significance and i'd rather avoid alleging that there is some proper course or \nprocess for experiencing the things that the other major arcana \ncards detail, so i'm gonna try to avoid that. but i like the power and potential that tarot gives to a figure wholly unbound by capitalist expectations of productivity or colonialist expectations of conquest and mastery. the flower is a white rose, symbolic of liberty, the bindle stick foreshadows the long journey ahead, and the white dog symbolizes how sometimes dogs are white and people have them."

let descrip58 = "today's card is the Magician, sometimes referred to as the Magus, the Juggler, or the Artisan. I've dubbed the magician the patron saint of tryhards, the archetypal figure who is working very hard to be good at something, usually a practical skill or craft. there is a layer of showmanship and flimsy charisma built in to his whole deal, maybe even some deceit or sleight of hand, but he is genuinely skilled through careful application of practice. I like to think of the magician as representative of the staggering difficulty of learning a new discipline. you never really feel like you aren't faking it, and every new twist can be excruciating, but the magician implores you to keep up the pursuit and never let 'em see you sweat. i wanted the art to depict someone who seems like he's constantly thinking 'i look so cool right now'. something i really love about the magician card is its direct acknowledgment of the minor arcana-- in most depictions the figure is directly manipulating a wand, a sword, a pentacle and a cup, and you don't really get that direct tie to the four suits anywhere else in the majors. this is a guy who's just figuring it out, and even if he seems a little goofy or arrogant, its because he feels the need to hustle to prove himself! be nice to this gator man, please. (i have a soft spot for this guy because i, too, am a tryhard)"

let descrip59 = "I like to think the first three cards of the major arcana form a little cycle of their own: the fool representing dumb luck and an absence of direction, the magician representing overexertion of skill and singularity of purpose, and the high priestess occupying the rational middle ground between the two. She embodies the sort of natural talent and prowess one develops when one has been doing something for so long it becomes inherent to one's identity. i think of ludological studies that privilege the idea of a 'flow state' when it comes to 'play'. to truly enjoy and have fun with a practice, some folks allege that you need to abandon the more critical parts of your mind and relax into the natural rhythms of the activity. of course, that can only be achieved when you're already very good at something! but i think the trance of a passion realized is what the high priestess is all about. she's pretty cool! i really cherish those moments when all of the moving parts of a difficult activity suddenly come together. i think skating and forms of movement are some of the easiest indicators of incorporating a skill into one's identity: when using the equipment becomes second nature to someone, it's really apparent. this is true of folks who are real good at musical instruments, or using certain computer programs, or drawing and painting, etc etc and not just athletics! but sports are some of the easiest visual signifiers, so here she is. also the high priestess is meant to be a 'fierce individualist', which lends itself well to skating's punky sensibilities. gosh i sound like a dang nerd. anyway i hope you like her!"

let descrip60 = "the empress is meant to represent the highest expression of feminine virtue. she also explicitly represents fertility and motherhood. does that ick you out like it icks me out? even barring the concerns of all the women who cannot give birth out there (hello), placing such esteem on bodily functions gives me bizarro cult vibes where they expect all people to be pregnant as much as physically possible. tarot tries to hand-wave away the most grotesque implications by saying this is about fertility of ideas, and of being creatively nurturing, but the base notion is kinda unavoidable for me. so, the art-- i wanted to do two things. 1) i wanted to address the kind of horrifying implications of the card as \ni see them. 2) i didn't want to make a card about motherhood inherently negative, because it IS an incredible thing, and folks who are able to and choose to give birth absolutely are worth celebrating and paying attention to in a respectful way. so i hope it's clear that while the empress is sort of a wretched shambling thing, she also genuinely is a mother to all of her little slug babies. if you are taking the creativity mindset to this card, i think it's a card about how you have to have a LOT of irredeemable idea-children before you land on one that really actually works."

let descrip61 = "The Emperor is basically the crystallization of all four suits' kings-- he represents a rigid hierarchy of ideas and discipline that seems impenetrable. usually this card is pulled when the querant needs to confront a system of rules they've been experiencing friction with-- these can either be societal rules, or a set of personal beliefs. the emperor asks us to remember that although he is imposing, it is worth dethroning the vague authority that comes from title and ancestry alone. if the empress represents the germination of ideas, the emperor represents when those ideas have hardened into immovable stone, and have grown stubborn beyond use. i was thinking a lot about Giants when i was doing this card, and the place they hold in a lot of cosmic genesis stories-- great world-shaping beasts that are eventually put down, or made to slumber, or that otherwise vacate after they've shaped the planet. I think i have personal experience with adopting strict and overreaching value systems in order to survive and function at certain times of my life, which i've later recognized as \nobsolete and irrelevant. let the emperor shape your world for a little while, and then bid him adieu! the windmill is, perhaps too blatantly, a reference to 'tilting at windmills and the man of la mancha's ineffective adherence to a romantic tradition that probably never had any basis in reality."

let descrip62 = "traditionally this card is actually the Pope or the Pontiff, but there were attempt made to decentralize Christianity in the deck (which i think ultimately serves it) and the Hierophant is one of the terms that came out of it. This card finishes up the second little major arcana cycle which starts with the Empress. There is no hierarchy beyond the divine, after all! A hierophant is a speaker of ancient secrets and truths, a representative of even higher authority than the emperor. Consequently, this card advises the querant to confront the deepest paradigms that they've come to rely on- the ideals that, if overturned, would truly revolutionize their life. These are the sorts of shifts in belief that are so vast that life before and after are unrecognizable different. you don't necessarily need to have one if you draw this card, but it might be worth poking around your nearly unconscious assumptions about how the world works. the things that lie in the dark might eventually fester and become unrecognizable to you. the art!! i really like horror when the scope is mind-fracturing, when the thing that is really terrifying is the depth of human ignorance and our inability to cope with reality's strange mechanisms. and that dovetails nicely with the representative of greater truths, i think! it's not necessarily malicious or evil, but it is big, and scary, and hard to comprehend all at once. so here is our little hierophant."

let descrip63 = "this card is fairly popular in media which features tarot because it's a pretty surefire way to signal a romantic subplot, but the actual meaning of the card is a lil more complicated. the rider-waite smith deck uses heavy symbolism from Adam and Eve, which hints towards the deeper interpretation. While this is certainly a card about the blissful exuberance of love-- about the wide-eyed idealism that new romantic ventures can impart to the querant-- it also implicitly references the compromise that results naturally from two different minds coming together. no relationship is completely flawless, and some things must be given up or altered in order to pursue a more perfect happiness (this sounds a lot like the concept of the 'fortunate fall' theory in Genesis, if you're familiar). i think in general it's good to remember that overindulgence in romance and relationships, while wildly exhilarating sometimes, can lead to neglect of the self. the lovers is just a card that encapsulates both sides of that truth! it's also the card associated with Geminis, so the two-facedness is really front and center."

let descrip64 = "todays card is THE CHARIOT, a card that is all about forward momentum. since chariots were war machines, there is a sense that this card has something to do with conquest and running down your dreams-- i don't know if i like that interpretation! i like to think of it more as having to do with the freedom of motion. i love taking road trips, especially unplanned ones and ones that are way further than people tend to go. there's something about the sense of 'progress' without doing much of anything that really soothes my lizard brain. this is a card which advises being 'driven', or determined, and making your way towards the destination. toot toot outta my way baybeee!!"

let descrip65 = "todays card is ADJUSTMENT, traditionally named JUSTICE. i like adjustment better because it stays away from the moral implications of the term justice (and who can think of the latter word without picturing a courtroom or a lady in a blindfold with scales and a sword?). adjustment as a card refers to the great equalization of things, how everything returns to a set point of relative inaction and simplicity. this broad sentiment is available in science and spirituality-- it seems that everything trends towards balance eventually! in drawing this card i was thinking about how a lot of the conversations around climate change and mounting military and social tensions predict 'the end of the world', but really what is forecasted is that the world will rebalance, just in a way that is unlivable for humanity. maybe that's bleak if you're big on anthropocentrism! but i also think it's hard to think about 'justice' as a concept right now without thinking very bleakly."

let descrip66 = "todays card is, fittingly, the hermit. he's an icon for the lonely hearts and the introspective, for taking time to yourself and growing individually. i think it's important to do this from time to time, but i definitely lean hard into being guarded and distant too often. it's not a bad thing but don't lose yourself to it!"

let descrip67 = "todays card is THE WHEEL (of fortune). You might also call this card 'chance'! the wheel of fortune has a long and storied symbolic history and many hilarious illustrations ranging waaaay back into history. it is, put reductively, the philosophy that what goes up comes down! there is no placating fate, you just take the cards you're dealt. rich today, poor tomorrow. etc etc etc. i tried to imbue this card with a little more passivity because oftentimes the wheel of fortune takes on kind of a moralistic tone that i think goes against its very nature."

let descrip68 = "this week's card is STRENGTH! Tarot is a magic system that dares to ask the age-old question 'what is true strength?' and answer it with 'it's when a lady can take down a lion' and i think that's beautiful. But for real this is a card that usually refers to inner strength, to overcoming a particularly difficult struggle, and to trusting one's bravery over believing that one is physically stronger than one's foes. But c'mon. the card is called strength! As for the art, it's hard to improve on woman wrestles a lion triumphantly, so i just tried to do my best gentileschi and put some feeling into it. if you see me at the gym, this is the build im going for."

let descrip69 = "this week's card is THE HANGED MAN. this is an interesting card imo! what i like most about it is the sense of unease it can foster because it defamiliarizes recognizable symbols in a new context. the hanged man is not there unwillingly, and he is not dying! he is serene and contemplative as he hangs upside down from something like a gallows, which conjures thoughts of torturous punishment. neat! that's magical thinking done right, if you ask me. this card usually indicates a momentary sacrifice or willful suspension of a cherished activity for a purpose. have you ever felt the weird ecstasy of hunger after fasting for a day or two? i think that's pretty near to what this card is all about. have a strange one, loves."

let descrip70 = "Today's card is DEATH, which notably does not mean that somebody in the querant's life is going to die soon or has died recently. Death in tarot's systems has more to do with state change. There are plenty of cards that indicate a coming shift, but Death clarifies that this is one that will be a) drastic, b) unavoidable, and c) there is no way to prepare for it or predict what comes after. this is why it still has a reputation for being a pretty scary card! any radical change can be uncomfortable, especially with the corollaries this card implies, but death is also notoriously ambivalent. as for the art, my main restriction for myself was No Spooky Skeletons. i just find them kind of overused as\n a memento mori. i wanted death to be a big force of nature that doesn't care about your bones."

let descrip71 = "today's card is TEMPERANCE, a card referring to one of the divine virtues! this is the virtue of moderation, not necessarily related to prohibition. this is a card that indicates a need for balance, for dilution of extremes and coolness of temper. the four cardinal virtues are generally thought of less than their sexier counterparts, the seven deadly sins, and temperance is maybe one of the most forgotten even of those, but it's an interesting concept to incorporate as a core tenet of your belief in what is 'good', i think. pushed to its logical conclusion, you could argue it stands in stark contrast to the idea of a universal good or possibility of a responsible all-powerful figure. and yet..! the 'traditional' imagery for temperance in tarot is an ambiguously sexed angel pouring water into wine, and sometimes you just want to draw a cool enby, so thank you for indulging me as\n i hewed pretty \nclose to that motif."

let descrip72 = "This card is certainly not a positive draw, but it's maybe not as negative as it first appears. The devil in tarot's magic system stands for the greatest achievement of the material-- the representation of the physical and the worldly. Usually this card indicates that the querant is overly reliant / being tempted by the ephemeral pleasures of the real and ignoring their spiritual and emotional needs. The devil may be a villain, but he is nothing without the power of seduction that material wealth promises, and this card indicates a challenge for the querant in that area. As for the art! I wanted to do something with how 'trapped' the devil is, since that is such a prominent message in Christianity and also in tarot's interpretation, but in the end I had trouble resisting the urge to draw the spooky goat man. so here he is! I took little bits of various devils in folklore and old depictions to fill out his chimeric visage. i think he's quite handsome."

let descrip73 = "Today's card is THE TOWER. there are plenty of cards that seem like bad news, but nothing quite tops the Tower in terms of There Is No Positive Way To Interpret This. The tower is about a fall from grace, the crumbling of the querant's hubris, the unfavorable judgment of their spiritual self-imprisonment. it is a portent of present and future doom, and comes with a side of telling the querant they deserved it on some level. whether that's because the querant was too proud or too narrow minded, its referent is pretty clearly the old tower of babel parable."

let descrip74 = "Today's card is THE STAR, a card with a fairly important place in the major arcana. Immediately following the wreck of the tower, the star promises a sort of hope. Of course, it's not the hope that one might be yearning for-- this is still a magic system bent on subverting expectations. Instead, it's the hope that comes from realizing your personal failings are minuscule and irrelevant in most scopes. The star is a card that deals with the Burkean sublime, a popular literary motif for Frankenstein readers everywhere-- the awe of the grandeur of the world around you, the way the fear of one's meaninglessness intermingles with the graciousness of getting to experience the enormity of nature. Such a complicated feeling, I feel like it's natural conclusion is in cosmic horror. looking to the stars at night, do you feel the sense of scale? is it comforting, or does it fill you with a creeping dread? that's what the star asks you to contend with, in the wreckage of humanity's great crumbling tower of artifice. as for the art, i like the idea of big weird aliens that aren't necessarily menacing so much as they are incomprehensible. and yeah, they could probably squish you like an ant-- but how many ants do you see in a day that you don't squish?"

const cards = [
  { img: card1, summary: descrip1, title: 'Ace of Wands', code: 'waac'},
  { img: card2, summary: descrip2, title: 'Two of Wands', code: 'wa02' },
  { img: card3, summary: descrip3, title: 'Three of Wands', code: 'wa03' },
  { img: card4, summary: descrip4, title: 'Four of Wands', code: 'wa04' },
  { img: card5, summary: descrip5, title: 'Five of Wands', code: 'wa05' },
  { img: card6, summary: descrip6, title: 'Six of Wands', code: 'wa06' },
  { img: card7, summary: descrip7, title: 'Seven of Wands', code: 'wa07' },
  { img: card8, summary: descrip8, title: 'Eight of Wands', code: 'wa08' },
  { img: card9, summary: descrip9, title: 'Nine of Wands', code: 'wa09' },
  { img: card10, summary: descrip10, title: 'Ten of Wands', code: 'wa10' },
  { img: card11, summary: descrip11, title: 'Page of Wands', code: 'wapa'},
  { img: card12, summary: descrip12, title: 'Knight of Wands', code: 'wakn'},
  { img: card13, summary: descrip13, title: 'Queen of Wands', code: 'waqu' },
  { img: card14, summary: descrip14, title: 'King of Wands', code: 'waki' },
  { img: card15, summary: descrip15, title: 'Ace of Cups', code: 'cuac' },
  { img: card16, summary: descrip16, title: 'Two of Cups', code: 'cu02' },
  { img: card17, summary: descrip17, title: 'Three of Cups', code: 'cu03' },
  { img: card18, summary: descrip18, title: 'Four of Cups', code: 'cu04' },
  { img: card19, summary: descrip19, title: 'Five of Cups', code: 'cu05' },
  { img: card20, summary: descrip20, title: 'Six of Cups', code: 'cu06' },
  { img: card21, summary: descrip21, title: 'Seven of Cups', code: 'cu07' },
  { img: card22, summary: descrip22, title: 'Eight of Cups', code: 'cu08' },
  { img: card23, summary: descrip23, title: 'Nine of Cups', code: 'cu09' },
  { img: card24, summary: descrip24, title: 'Ten of Cups', code: 'cu10' },
  { img: card25, summary: descrip25, title: 'Page of Cups', code: 'cupa' },
  { img: card26, summary: descrip26, title: 'Knight of Cups', code: 'cukn' },
  { img: card27, summary: descrip27, title: 'Queen of Cups', code: 'cuqu' },
  { img: card28, summary: descrip28, title: 'King of Cups', code: 'cuki' },
  { img: card29, summary: descrip29, title: 'Ace of Coins', code: 'peac'},
  { img: card30, summary: descrip30, title: 'Two of Coins', code: 'pe02' },
  { img: card31, summary: descrip31, title: 'Three of Coins', code: 'pe03'},
  { img: card32, summary: descrip32, title: 'Four of Coins', code: 'pe04'},
  { img: card33, summary: descrip33, title: 'Five of Coins', code: 'pe05'},
  { img: card34, summary: descrip34, title: 'Six of Coins', code: 'pe06' },
  { img: card35, summary: descrip35, title: 'Seven of Coins', code: 'pe07' },
  { img: card36, summary: descrip36, title: 'Eight of Coins', code: 'pe08' },
  { img: card37, summary: descrip37, title: 'Nine of Coins', code: 'pe09' },
  { img: card38, summary: descrip38, title: 'Ten of Coins', code: 'pe10' },
  { img: card39, summary: descrip39, title: 'Page of Coins', code: 'pepa' },
  { img: card40, summary: descrip40, title: 'Knight of Coins', code: 'pekn' },
  { img: card41, summary: descrip41, title: 'Queen of Coins', code: 'pequ' },
  { img: card42, summary: descrip42, title: 'King of Coins', code: 'peki' },
  { img: card43, summary: descrip43, title: 'Ace of Swords', code: 'swac' },
  { img: card44, summary: descrip44, title: 'Two of Swords', code: 'sw02' },
  { img: card45, summary: descrip45, title: 'Three of Swords', code: 'sw03' },
  { img: card46, summary: descrip46, title: 'Four of Swords', code: 'sw04' },
  { img: card47, summary: descrip47, title: 'Five of Swords', code: 'sw05' },
  { img: card48, summary: descrip48, title: 'Six of Swords', code: 'sw06' },
  { img: card49, summary: descrip49, title: 'Seven of Swords', code: 'sw07' },
  { img: card50, summary: descrip50, title: 'Eight of Swords', code: 'sw08' },
  { img: card51, summary: descrip51, title: 'Nine of Swords', code: 'sw09' },
  { img: card52, summary: descrip52, title: 'Ten of Swords', code: 'sw10' },
  { img: card53, summary: descrip53, title: 'Page of Swords', code: 'swpa' },
  { img: card54, summary: descrip54, title: 'Knight of Swords', code: 'swkn' },
  { img: card55, summary: descrip55, title: 'Queen of Swords', code: 'swqu' },
  { img: card56, summary: descrip56, title: 'King of Swords', code: 'swki' },
  { img: card57, summary: descrip57, title: 'The Fool', code: 'ar00'},
  { img: card58, summary: descrip58, title: 'The Magician', code: 'ar01'},
  { img: card59, summary: descrip59, title: 'The High Priestess', code: 'ar02'},
  { img: card60, summary: descrip60, title: 'The Empress', code: 'ar03'},
  { img: card61, summary: descrip61, title: 'The Emperor', code: 'ar04'},
  { img: card62, summary: descrip62, title: 'The Hierophant', code: 'ar05'},
  { img: card63, summary: descrip63, title: 'The Lovers', code: 'ar06'},
  { img: card64, summary: descrip64, title: 'The Chariot', code: 'ar07'},
  { img: card65, summary: descrip65, title: 'Adjustment', code: 'ar11'},
  { img: card66, summary: descrip66, title: 'The Hermit', code: 'ar09'},
  { img: card67, summary: descrip67, title: 'The Wheel of Fortune', code: 'ar10'},
  { img: card68, summary: descrip68, title: 'Strength', code: 'ar08'},
  { img: card69, summary: descrip69, title: 'The Hanged Man', code: 'ar12'},
  { img: card70, summary: descrip70, title: 'Death', code: 'ar13'},
  { img: card71, summary: descrip71, title: 'Temperance', code: 'ar14'},
  { img: card72, summary: descrip72, title: 'The Devil', code: 'ar15'},
  { img: card73, summary: descrip73, title: 'The Tower', code: 'ar16'},
  { img: card74, summary: descrip74, title: 'The Star', code: 'ar17'}]

export default cards;